### ISSUE TITLE
gmm_svae_synth assertion error

### ISSUE THREAD

**Issue by andymiller** [mattjj/svae#2]
Hey Matty --- I'm seeing an assertion error during the `resnet_decode` step when running the `gmm_svae_synth.py` example as is:

```
│/Users/acm/Dropbox/Proj/svae/svae/forward_models.pyc in resnet_decode(z, phi)
│     81 def resnet_decode(z, phi):
│     82     phi_linear, phi_mlp = phi
│---> 83     return add(linear_decode(z, phi_linear), mlp_decode(z, phi_mlp, tanh_scale=
│2., sigmoid_output=False))
│     84     # return linear_decode(z, phi_linear)
│     85
│
│/Users/acm/Dropbox/Proj/svae/svae/util.py in wrapped(a, b)
│    134         if shape(a) != shape(b):
│    135             print shape(a), shape(b)
│--> 136         assert shape(a) == shape(b)
│    137         return binop(a, b)
│    138     return wrapped
│
│AssertionError:
```

It looks like the param sizes passed to add have shapes

```
((150, 10, 2), (150, 10, 4)) ((150, 10, 2), (150, 10, 2))
```

so the second set of params coming from `linear_decode` has a last dimension twice as big as the second set of params coming from `mlp_decode`.  

Is one passing back a dense covariance and the other passing back a diagonal covariance?

**Comment by mattjj** [comment]
Leaving this note for others: the file is working on the gmm-synth-better-plots branch, which needs to be reconciled with master.

**Comment by mattjj** [comment]
See the discussion in #4. The example should be working in the current master, and I cleaned up the code for neural nets (there's no more forward_models.py or recognition_models.py) so these shape problems should be gone.
