### ISSUE TITLE
Wired results after running gmm_svae_synth. py

### ISSUE THREAD

**Issue by JerryDing** [mattjj/svae#3]
After running the script gmm_svae_synth.py (around one and a half hours on a Mac desktop computer), the results seem not reasonable (running_gmm_2000.png). So I just wondering if  there is anything wrong with the script? 
![image](https://cloud.githubusercontent.com/assets/876040/17384417/f93e7f62-5990-11e6-9578-787242a99075.png)

**Comment by mattjj** [comment]
Yeah I left the example code in a broken state. It might be less broken on the gmm-synth-better-plots branch, but I'm not sure. I've been busy with a job search but I hope to come back and fix things up at some point in the not-too-distant future.

**Comment by mattjj** [comment]
See the discussion in #4. The example should be working in the master branch now.
