### ISSUE TITLE
install dependency error

### ISSUE THREAD

**Issue by ghost** [mattjj/svae#7]
Hi, i tried to re-produce the results in paper using this code, but i meet the following confusing errors:
i run instruction `python setup.py build_ext --inplace` on ubuntu 14.04 with python 2.7.6, scipy, numpy and gcc 4.7.3 correctly installed. Could anyone help me? Thanks! 
So sorry for placing so long errors here.

- andrew@ubuntu1:~/xu/svae$ python setup.py build_ext --inplace
- `missing cimport in module 'scipy.linalg.cython_lapack': ./svae/cython_linalg_grads.pxd
- missing cimport in module 'scipy.linalg.cython_blas': ./svae/cython_linalg_grads.pxd
- missing cimport in module 'scipy.linalg.cython_lapack': ./svae/cython_util.pxd
- missing cimport in module 'scipy.linalg.cython_blas': ./svae/cython_util.pxd
- missing cimport in module 'scipy.linalg.cython_lapack': ./svae/lds/cython_gaussian_grads.pxd
- missing cimport in module 'scipy.linalg.cython_blas': ./svae/lds/cython_gaussian_grads.pxd
- missing cimport in module 'scipy.linalg.cython_lapack': svae/lds/cython_lds_inference.pyx
- missing cimport in module 'scipy.linalg.cython_blas': svae/lds/cython_lds_inference.pyx
- missing cimport in module 'scipy.linalg.cython_blas': svae/hmm/cython_hmm_inference.pyx
- Compiling tests/test_cython_linalg_grads.pyx because it changed.
- Compiling tests/test_cython_gaussian_grads.pyx because it changed.
- Compiling svae/lds/cython_lds_inference.pyx because it changed.
- Compiling svae/hmm/cython_hmm_inference.pyx because it changed.
- Cythonizing svae/hmm/cython_hmm_inference.pyx
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
- ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:0: 'scipy.linalg.cython_blas.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
- ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:0: 'ddot.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
-                                      ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:38: Name 'ddot' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
- ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:0: 'dgemm.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
-                                            ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:44: Name 'dgemm' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
- ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:0: 'dgemv.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- import numpy as np
- cimport numpy as np
- import numpy.random as npr
- from scipy.linalg.cython_blas cimport ddot, dgemm, dgemv
-                                                   ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:7:51: Name 'dgemv' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:3:0: 'dsymv.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
-                                      ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:3:38: Name 'dsymv' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
-                                             ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:3:45: Name 'ddot' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
-                                                   ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:3:51: Name 'dgemm' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
-                                                          ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:3:58: Name 'dgemv' not declared in module 'scipy.linalg.cython_blas'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
- ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:0: 'scipy.linalg.cython_lapack.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
- ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:0: 'dtrtrs.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
-                                        ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:40: Name 'dtrtrs' not declared in module 'scipy.linalg.cython_lapack'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
- ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:0: 'dpotrf.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
-                                                ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:48: Name 'dpotrf' not declared in module 'scipy.linalg.cython_lapack'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
- ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:0: 'dpotrs.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
-                                                        ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:56: Name 'dpotrs' not declared in module 'scipy.linalg.cython_lapack'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
- ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:0: 'dpotri.pxd' not found
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
- # cython: boundscheck=False, nonecheck=False, wraparound=False, cdivision=True
- 
- from scipy.linalg.cython_blas cimport dsymv, ddot, dgemm, dgemv
- from scipy.linalg.cython_lapack cimport dtrtrs, dpotrf, dpotrs, dpotri
-                                                                ^
- ------------------------------------------------------------
- 
- svae/cython_util.pxd:4:64: Name 'dpotri' not declared in module 'scipy.linalg.cython_lapack'
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-             ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:13: undeclared name not builtin: dgemv
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                   ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:19: Cannot convert 'int *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                       ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:23: Cannot convert 'int *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                           ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:27: Cannot convert 'double *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                                 ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:33: Cannot convert 'double *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                                                    ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:52: Cannot convert 'int *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                                                        ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:56: Cannot convert 'double *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-     for t in range(T):
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-                                                                     ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:85:69: Cannot convert 'int *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-               &zero, &in_potential[0], &inc)
-              ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:86:14: Cannot convert 'double *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-               &zero, &in_potential[0], &inc)
-                     ^
- ------------------------------------------------------------
- 
- svae/hmm/cython_hmm_inference.pyx:86:21: Cannot convert 'double *' to Python object
- 
- Error compiling Cython file:
- ------------------------------------------------------------
- ...
-         themax = max_vector(node_params[t])
-         for i in range(N):
-             alpha[t,i] = in_potential[i] * exp(node_params[t,i] - themax)
-         lognorm += log(normalize_inplace(alpha[t])) + themax
-         dgemv('T', &N, &N, &one, &pair_params[0,0], &N, &alpha[t,0], &inc,
-               &zero, &in_potential[0], &inc)
-                                       ^
- ------------------------------------------------------------
- 
- 
- svae/hmm/cython_hmm_inference.pyx:86:39: Cannot convert 'int *' to Python object
- Traceback (most recent call last):
-   File "setup.py", line 6, in <module>
-     ext_modules=cythonize('**/*.pyx'),
-   File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
-     cythonize_one(*args[1:])
-   File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
-     raise CompileError(None, pyx_file)
- Cython.Compiler.Errors.CompileError: svae/hmm/cython_hmm_inference.pyx`

**Comment by mattjj** [comment]
I'm currently rewriting the code. Try working from the commit 7878260 (which is the one we were using while discussing #4).

That said, the build process works fine for me on the current master branch. You probably need the most up-to-date versions of every package, particularly cython (tested on 0.24.1 and 0.25.1) and scipy (tested on 0.18.1 and later). I'm also using a newer compiler (gcc 5.3 and later), though I don't think that should matter.

**Comment by mattjj** [comment]
We'll try to make the build process easier by NIPS!

**Comment by ghost** [comment]
Hi, @mattjj  Thank you!
I have found those errors were caused by my python enviroment.

**Comment by mattjj** [comment]
Great!
