### ISSUE TITLE
NIW natural parameterization

### ISSUE THREAD

**Issue by jcapde** [mattjj/svae#9]
Hi! Thanks for sharing the code and congrats for this amazing article!

I have a particular doubt about the natural parameterisation of the NIW distribution and I saw that in your code there is a function to re-parameterise it (`standard_to_natural()` in `svae/distributions/niw.py`). In particular, I don't exactly see where the outer product in parameter `S`. Do you know any reference where I can check out the natural parameterisation for the NIW distribution (I couldn't find any)?

Many thanks in advance!

**Comment by jcapde** [comment]
I think I've found it. I was missing the fact that matrix parameters are vectorised in the Inv-Wishart exponential form and the trace of becomes their vector dot product (**kappa*m<sup>T</sup>m**). Then, the outer product makes totally sense, since the resulting matrix will also be vectorised and the the dot product with X will give us the missing term **kappa*m<sup>T</sup>X<sup>-1</sup>m**. Thanks again!

**Comment by mattjj** [comment]
Thanks for your question, and for answering it too! It would be good to document these things better. My [pybasicbayes repo](https://github.com/mattjj/pybasicbayes) follows more standard conventions.
